:repository-owner: fatlab101
:repository-name: FixedString
:arduino-libs: arduino-libraries

An Arduino stack based fixed string class:


```cpp

#include <FixedString.h>

Replace:

char buffer[24];
strcpy(buffer,"This is my");
strcat(buffer," string");
Serial.println(buffer);


With:

FixedString<24> buffer="This is my";
buffer+=" string";
Serial.println(buffer.c_str());


```


== License ==

Copyright (c) 2022 Fatlab Software.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
